services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: aws-quiz-backend
    restart: unless-stopped
    ports:
      - "5001:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      # AWS DynamoDB Configuration
      AWS_REGION: us-east-2
      DYNAMODB_QUESTIONS_TABLE: aws-quiz-questions
      DYNAMODB_GAME_SESSIONS_TABLE: aws-quiz-game-sessions
      DYNAMODB_LEADERBOARD_TABLE: aws-quiz-leaderboard
    volumes:
      - ./backend/data:/app/data
      - ./backend/.env:/app/.env:ro
    networks:
      - aws-quiz-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: aws-quiz-frontend
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - REACT_APP_API_URL=http://aws-quiz-backend:5000/api
    depends_on:
      - backend
    networks:
      - aws-quiz-network

networks:
  aws-quiz-network:
    driver: bridge
