version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5001:5000"
    environment:
      - NODE_ENV=development
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - DYNAMODB_TABLE_PREFIX=aws-quiz-local
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - aws-quiz-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ./frontend
    ports:
      - "3001:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5001/api
      - FAST_REFRESH=true
      - WDS_SOCKET_HOST=localhost
      - WDS_SOCKET_PORT=3000
      - WDS_SOCKET_PATH=/ws
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - aws-quiz-network
    depends_on:
      backend:
        condition: service_healthy

networks:
  aws-quiz-network:
    driver: bridge

volumes:
  node_modules_backend:
  node_modules_frontend:
