services:
  # Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: aws-quiz-backend-local
    restart: unless-stopped
    ports:
      - "5001:5000"
    environment:
      NODE_ENV: development
      PORT: 5000
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/.env:/app/.env:ro
    networks:
      - aws-quiz-network


  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: aws-quiz-frontend-local
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5001/api
      - DISABLE_ESLINT_PLUGIN=true
      - GENERATE_SOURCEMAP=false
      - FAST_REFRESH=true
      - WDS_SOCKET_HOST=localhost
      - WDS_SOCKET_PORT=3000
      - WDS_SOCKET_PATH=/ws
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - aws-quiz-network
    depends_on:
      backend:
        condition: service_healthy

networks:
  aws-quiz-network:
    driver: bridge

volumes:
  node_modules_backend:
  node_modules_frontend: